from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Callable, Protocol, runtime_checkable

if TYPE_CHECKING:  # pragma: no cover
    from robot_sim.application.dto import IKRequest, TrajectoryRequest
    from robot_sim.application.services.metrics_service import MetricsService
    from robot_sim.application.services.playback_service import PlaybackFrame, PlaybackService
    from robot_sim.application.services.task_error_mapper import TaskErrorMapper
    from robot_sim.application.use_cases.plan_trajectory import PlanTrajectoryUseCase
    from robot_sim.application.use_cases.run_benchmark import RunBenchmarkUseCase
    from robot_sim.application.use_cases.run_ik import RunIKUseCase
    from robot_sim.domain.error_projection import ErrorPresentation
    from robot_sim.model.benchmark_report import BenchmarkReport
    from robot_sim.model.fk_result import FKResult
    from robot_sim.model.ik_result import IKResult
    from robot_sim.model.imported_robot_result import ImportedRobotResult
    from robot_sim.model.pose import Pose
    from robot_sim.model.robot_catalog_entry import RobotCatalogEntry
    from robot_sim.model.session_state import SessionState
    from robot_sim.model.solver_config import IKConfig
    from robot_sim.model.task_snapshot import TaskSnapshot
    from robot_sim.model.trajectory import JointTrajectory
    from robot_sim.presentation.state_store import StateStore
    from robot_sim.presentation.thread_orchestrator import ThreadOrchestrator
    from robot_sim.application.importers.importer_descriptor import ImporterDescriptor


@runtime_checkable
class RuntimeViewContract(Protocol):
    """Minimal runtime projection/read contract required by coordinators."""

    @property
    def state(self) -> 'SessionState': ...

    @property
    def state_store(self) -> 'StateStore': ...

    @property
    def export_root(self) -> Path: ...

    @property
    def task_error_mapper(self) -> 'TaskErrorMapper': ...


@runtime_checkable
class RobotWorkflowContract(Protocol):
    def robot_entries(self) -> list['RobotCatalogEntry']: ...
    def importer_entries(self) -> list['ImporterDescriptor']: ...
    def load_robot(self, name: str) -> 'FKResult': ...
    def import_robot(self, source: str, importer_id: str | None = None) -> 'ImportedRobotResult': ...
    def save_current_robot(self, rows: object = None, home_q: object = None, name: str | None = None) -> Path: ...
    def run_fk(self, q: object = None) -> 'FKResult': ...


@runtime_checkable
class MotionWorkflowContract(Protocol):
    ik_use_case: 'RunIKUseCase'
    trajectory_use_case: 'PlanTrajectoryUseCase'
    benchmark_use_case: 'RunBenchmarkUseCase'
    playback_service: 'PlaybackService'

    def solver_defaults(self) -> dict[str, object]: ...
    def trajectory_defaults(self) -> dict[str, object]: ...
    def build_target_pose(self, values6: object, orientation_mode: str = 'rvec') -> 'Pose': ...
    def build_ik_request(self, values6: object, **kwargs: object) -> 'IKRequest': ...
    def apply_ik_result(self, req: 'IKRequest', result: 'IKResult') -> None: ...
    def run_ik(self, values6: object, **kwargs: object) -> 'IKResult': ...
    def build_benchmark_config(self, **kwargs: object) -> 'IKConfig': ...
    def run_benchmark(self, config: 'IKConfig | None' = None, *, execution_graph: dict[str, object] | None = None) -> 'BenchmarkReport': ...
    def trajectory_goal_or_raise(self) -> object: ...
    def build_trajectory_request(self, **kwargs: object) -> 'TrajectoryRequest': ...
    def plan_trajectory(self, **kwargs: object) -> 'JointTrajectory': ...
    def apply_trajectory(self, traj: 'JointTrajectory') -> None: ...
    def current_playback_frame(self) -> 'PlaybackFrame': ...
    def set_playback_frame(self, frame_idx: int) -> 'PlaybackFrame': ...
    def next_playback_frame(self) -> 'PlaybackFrame | None': ...
    def set_playback_options(self, *, speed_multiplier: float | None = None, loop_enabled: bool | None = None) -> None: ...
    def ensure_playback_ready(self, strict: bool = True) -> None: ...


@runtime_checkable
class ExportWorkflowContract(Protocol):
    def export_trajectory_bundle(self, name: str = 'trajectory_bundle.npz') -> Path: ...
    def export_trajectory_metrics(self, name: str = 'trajectory_metrics.json', metrics: dict[str, object] | None = None) -> Path: ...
    def export_session(self, name: str = 'session.json', *, telemetry_detail: str = 'full') -> Path: ...
    def export_package(self, name: str = 'robot_sim_package.zip', *, telemetry_detail: str = 'minimal') -> Path: ...
    def export_benchmark(self, name: str = 'benchmark_report.json') -> Path: ...
    def export_benchmark_cases_csv(self, name: str = 'benchmark_cases.csv') -> Path: ...


@runtime_checkable
class RobotFacadeContract(Protocol):
    def robot_entries(self) -> list['RobotCatalogEntry']: ...
    def importer_entries(self) -> list['ImporterDescriptor']: ...
    def load_robot(self, name: str) -> 'FKResult': ...
    def import_robot(self, source: str, importer_id: str | None = None) -> 'ImportedRobotResult': ...
    def save_current_robot(self, rows: object = None, home_q: object = None, name: str | None = None) -> Path: ...
    def run_fk(self, q: object = None) -> 'FKResult': ...


@runtime_checkable
class SolverFacadeContract(Protocol):
    ik_use_case: 'RunIKUseCase'

    def solver_defaults(self) -> dict[str, object]: ...
    def build_target_pose(self, values6: object, orientation_mode: str = 'rvec') -> 'Pose': ...
    def build_ik_request(self, values6: object, **kwargs: object) -> 'IKRequest': ...
    def apply_ik_result(self, req: 'IKRequest', result: 'IKResult') -> None: ...


@runtime_checkable
class TrajectoryFacadeContract(Protocol):
    trajectory_use_case: 'PlanTrajectoryUseCase'

    def trajectory_defaults(self) -> dict[str, object]: ...
    def build_trajectory_request(self, **kwargs: object) -> 'TrajectoryRequest': ...
    def apply_trajectory(self, traj: 'JointTrajectory') -> None: ...


@runtime_checkable
class PlaybackFacadeContract(Protocol):
    playback_service: 'PlaybackService'

    def set_playback_frame(self, frame_idx: int) -> 'PlaybackFrame': ...
    def next_playback_frame(self) -> 'PlaybackFrame | None': ...
    def set_playback_options(self, *, speed_multiplier: float | None = None, loop_enabled: bool | None = None) -> None: ...
    def ensure_playback_ready(self, strict: bool = True) -> None: ...


@runtime_checkable
class BenchmarkFacadeContract(Protocol):
    benchmark_use_case: 'RunBenchmarkUseCase'

    def build_benchmark_config(self, **kwargs: object) -> 'IKConfig': ...


@runtime_checkable
class ExportFacadeContract(Protocol):
    def export_trajectory_bundle(self, name: str = 'trajectory_bundle.npz') -> Path: ...
    def export_trajectory_metrics(self, name: str = 'trajectory_metrics.json', metrics: dict[str, object] | None = None) -> Path: ...
    def export_session(self, name: str = 'session.json', *, telemetry_detail: str = 'full') -> Path: ...
    def export_package(self, name: str = 'robot_sim_package.zip', *, telemetry_detail: str = 'minimal') -> Path: ...
    def export_benchmark(self, name: str = 'benchmark_report.json') -> Path: ...
    def export_benchmark_cases_csv(self, name: str = 'benchmark_cases.csv') -> Path: ...


@runtime_checkable
class ExportTaskView(Protocol):
    runtime_facade: RuntimeViewContract
    export_workflow: ExportWorkflowContract
    metrics_service: 'MetricsService'
    threader: 'ThreadOrchestrator'

    def project_task_started(self, task_kind: str, message: str) -> None: ...
    def project_task_registered(self, task_id: str, task_kind: str) -> None: ...
    def project_export_messages(self, *messages: str) -> None: ...
    def on_worker_failed(self, failure: object) -> None: ...
    def on_worker_cancelled(self) -> None: ...


@runtime_checkable
class SceneTaskView(Protocol):
    runtime_facade: RuntimeViewContract
    threader: 'ThreadOrchestrator'

    def build_scene_capture_request(self, path: Path) -> dict[str, object]: ...
    def project_task_started(self, task_kind: str, message: str) -> None: ...
    def project_task_registered(self, task_id: str, task_kind: str) -> None: ...
    def project_scene_fit(self) -> None: ...
    def project_scene_path_cleared(self) -> None: ...
    def project_scene_capture(self, result: object) -> None: ...
    def read_scene_obstacle_request(self) -> dict[str, object] | None: ...
    def project_scene_obstacles_updated(self, scene: object) -> None: ...
    def on_worker_failed(self, failure: object) -> None: ...
    def on_worker_cancelled(self) -> None: ...


@runtime_checkable
class IKTaskView(Protocol):
    motion_workflow: MotionWorkflowContract
    metrics_service: 'MetricsService'
    threader: 'ThreadOrchestrator'

    def read_ik_request(self) -> 'IKRequest': ...
    def project_task_started(self, task_kind: str, message: str) -> None: ...
    def project_task_registered(self, task_id: str, task_kind: str) -> None: ...
    def project_busy_state(self, busy: bool, reason: str = '') -> None: ...
    def project_ik_result(self, result: 'IKResult', summary: dict[str, object]) -> None: ...
    def on_ik_progress(self, payload: object) -> None: ...
    def on_ik_finished(self, result: object) -> None: ...
    def on_worker_failed(self, failure: object) -> None: ...
    def on_worker_cancelled(self) -> None: ...


@runtime_checkable
class TrajectoryTaskView(Protocol):
    motion_workflow: MotionWorkflowContract
    metrics_service: 'MetricsService'
    threader: 'ThreadOrchestrator'

    def read_trajectory_request(self) -> 'TrajectoryRequest': ...
    def project_task_started(self, task_kind: str, message: str) -> None: ...
    def project_task_registered(self, task_id: str, task_kind: str) -> None: ...
    def project_busy_state(self, busy: bool, reason: str = '') -> None: ...
    def project_trajectory_result(self, traj: 'JointTrajectory', metrics: dict[str, object], ee_points: object) -> None: ...
    def on_trajectory_finished(self, result: object) -> None: ...
    def on_worker_failed(self, failure: object) -> None: ...
    def on_worker_cancelled(self) -> None: ...


@runtime_checkable
class MainWindowActionView(Protocol):
    """Narrow contract consumed by ``MainWindowActionMixin``.

    The goal is to keep action handlers independent from the full window shell so future
    presentation splits do not require the old monolithic ``MainWindowLike`` surface.
    """

    status_panel: object
    target_panel: object
    robot_panel: object
    playback_panel: object
    scene_controller: object
    plots_manager: object
    playback_render_scheduler: object
    robot_coordinator: object
    playback_task_coordinator: object
    scene_coordinator: object
    export_task_coordinator: object

    def _runtime_ops(self) -> RuntimeViewContract: ...
    def _robot_ops(self) -> RobotWorkflowContract: ...
    def _playback_ops(self) -> MotionWorkflowContract: ...
    def _run_presented(self, callback: Callable[[], object], *, title: str = '错误') -> object: ...
    def _run_status_projected(self, callback: Callable[[], object], *, prefix: str) -> object: ...
    def _set_playback_running(self, running: bool) -> None: ...
    def _project_exception(self, exc: Exception | str, *, title: str = '错误') -> None: ...
    def _playback_status_text(self) -> str: ...
    def project_playback_frame(self, frame: object, live: bool = False) -> None: ...
    def read_robot_import_request(self) -> dict[str, object] | None: ...
    def project_robot_imported(self, result: 'ImportedRobotResult') -> None: ...


@runtime_checkable
class MainWindowTaskView(Protocol):
    """Narrow contract consumed by ``MainWindowTaskMixin``."""

    threader: 'ThreadOrchestrator'
    status_panel: object
    target_panel: object
    solver_panel: object
    benchmark_panel: object
    scene_controller: object
    plots_manager: object
    metrics_service: 'MetricsService'
    ik_task_coordinator: object
    trajectory_task_coordinator: object
    benchmark_task_coordinator: object
    status_coordinator: object

    def _runtime_ops(self) -> RuntimeViewContract: ...
    def _solver_ops(self) -> MotionWorkflowContract: ...
    def _trajectory_ops(self) -> MotionWorkflowContract: ...
    def _playback_ops(self) -> MotionWorkflowContract: ...
    def _run_presented(self, callback: Callable[[], object], *, title: str = '错误') -> object: ...
    def _set_busy(self, busy: bool, reason: str = '') -> None: ...
    def _build_solver_kwargs(self) -> dict[str, object]: ...
    def _playback_status_text(self) -> str: ...
    def _update_diagnostics_from_benchmark(self, summary: dict[str, object]) -> None: ...
    def _project_exception(self, exc: Exception | str, *, title: str = '错误') -> None: ...
    def project_trajectory_result(self, traj: 'JointTrajectory', metrics: dict[str, object], ee_points: object) -> None: ...


@runtime_checkable
class MainWindowUIContract(MainWindowActionView, MainWindowTaskView, Protocol):
    """UI-shell contract kept local to ``MainWindowUIMixin``.

    The UI mixin still needs a broad surface because it owns widget construction and
    projection methods, but that breadth is now localized instead of shared across all
    presentation mixins.
    """

    runtime_facade: RuntimeViewContract
    robot_workflow: RobotWorkflowContract
    motion_workflow: MotionWorkflowContract
    export_workflow: ExportWorkflowContract
    playback_threader: 'ThreadOrchestrator'
    window_cfg: dict[str, object]
    diagnostics_panel: object
    scene_widget: object
    right_tabs: object
    _error_boundary: object

    def setCentralWidget(self, widget: object) -> None: ...
    def on_load_robot(self) -> None: ...
    def on_import_robot(self) -> None: ...
    def on_save_robot(self) -> None: ...
    def on_fill_current_pose(self) -> None: ...
    def on_run_fk(self) -> None: ...
    def on_run_ik(self) -> None: ...
    def on_cancel_ik(self) -> None: ...
    def on_plan(self) -> None: ...
    def on_play(self) -> None: ...
    def on_pause(self) -> None: ...
    def on_stop_playback(self) -> None: ...
    def on_step(self) -> None: ...
    def on_seek_frame(self, idx: int) -> None: ...
    def on_playback_speed_changed(self, value: float) -> None: ...
    def on_playback_loop_changed(self, checked: bool) -> None: ...
    def on_fit_scene(self) -> None: ...
    def on_clear_scene_path(self) -> None: ...
    def on_capture_scene(self) -> None: ...
    def on_add_scene_obstacle(self) -> None: ...
    def on_clear_scene_obstacles(self) -> None: ...
    def build_scene_capture_request(self, path: Path) -> dict[str, object]: ...
    def read_scene_obstacle_request(self) -> dict[str, object] | None: ...
    def project_scene_obstacles_updated(self, scene: object) -> None: ...
    def on_run_benchmark(self) -> None: ...
    def on_export_session(self) -> None: ...
    def on_export_package(self) -> None: ...
    def on_export_benchmark(self) -> None: ...
    def _on_task_state_changed(self, snapshot: 'TaskSnapshot | None') -> None: ...
