from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class RuntimeViewContract(Protocol):
    """Minimal runtime projection/read contract required by coordinators."""

    @property
    def state(self) -> Any: ...

    @property
    def state_store(self) -> Any: ...

    @property
    def export_root(self) -> Any: ...

    @property
    def task_error_mapper(self) -> Any: ...


@runtime_checkable
class RobotWorkflowContract(Protocol):
    def robot_entries(self) -> Any: ...
    def importer_entries(self) -> Any: ...
    def load_robot(self, name: str) -> Any: ...
    def import_robot(self, source: str, importer_id: str | None = None) -> Any: ...
    def save_current_robot(self, rows=None, home_q=None, name: str | None = None) -> Any: ...
    def run_fk(self, q=None) -> Any: ...


@runtime_checkable
class MotionWorkflowContract(Protocol):
    ik_use_case: Any
    trajectory_use_case: Any
    benchmark_use_case: Any
    playback_service: Any

    def solver_defaults(self) -> dict[str, object]: ...
    def trajectory_defaults(self) -> dict[str, object]: ...
    def build_target_pose(self, values6, orientation_mode: str = 'rvec') -> Any: ...
    def build_ik_request(self, values6, **kwargs) -> Any: ...
    def apply_ik_result(self, req, result) -> None: ...
    def build_benchmark_config(self, **kwargs) -> Any: ...
    def build_trajectory_request(self, **kwargs) -> Any: ...
    def apply_trajectory(self, traj) -> None: ...
    def set_playback_frame(self, frame_idx: int) -> Any: ...
    def next_playback_frame(self) -> Any: ...
    def set_playback_options(self, *, speed_multiplier=None, loop_enabled=None) -> None: ...
    def ensure_playback_ready(self, strict: bool = True) -> None: ...


@runtime_checkable
class ExportWorkflowContract(Protocol):
    def export_trajectory_bundle(self, name: str = 'trajectory_bundle.npz') -> Any: ...
    def export_trajectory(self, name: str = 'trajectory_bundle.npz') -> Any: ...
    def export_trajectory_metrics(self, name: str = 'trajectory_metrics.json', metrics: dict[str, object] | None = None) -> Any: ...
    def export_session(self, name: str = 'session.json', *, telemetry_detail: str = 'full') -> Any: ...
    def export_package(self, name: str = 'robot_sim_package.zip', *, telemetry_detail: str = 'minimal') -> Any: ...
    def export_benchmark(self, name: str = 'benchmark_report.json') -> Any: ...
    def export_benchmark_cases_csv(self, name: str = 'benchmark_cases.csv') -> Any: ...


@runtime_checkable
class RobotFacadeContract(Protocol):
    def robot_entries(self) -> Any: ...
    def importer_entries(self) -> Any: ...
    def load_robot(self, name: str) -> Any: ...
    def import_robot(self, source: str, importer_id: str | None = None) -> Any: ...
    def save_current_robot(self, rows=None, home_q=None, name: str | None = None) -> Any: ...
    def run_fk(self, q=None) -> Any: ...


@runtime_checkable
class SolverFacadeContract(Protocol):
    ik_use_case: Any

    def solver_defaults(self) -> dict[str, object]: ...
    def build_target_pose(self, values6, orientation_mode: str = 'rvec') -> Any: ...
    def build_ik_request(self, values6, **kwargs) -> Any: ...
    def apply_ik_result(self, req, result) -> None: ...


@runtime_checkable
class TrajectoryFacadeContract(Protocol):
    trajectory_use_case: Any

    def trajectory_defaults(self) -> dict[str, object]: ...
    def build_trajectory_request(self, **kwargs) -> Any: ...
    def apply_trajectory(self, traj) -> None: ...


@runtime_checkable
class PlaybackFacadeContract(Protocol):
    playback_service: Any

    def set_playback_frame(self, frame_idx: int) -> Any: ...
    def next_playback_frame(self) -> Any: ...
    def set_playback_options(self, *, speed_multiplier=None, loop_enabled=None) -> None: ...
    def ensure_playback_ready(self, strict: bool = True) -> None: ...


@runtime_checkable
class BenchmarkFacadeContract(Protocol):
    benchmark_use_case: Any

    def build_benchmark_config(self, **kwargs) -> Any: ...


@runtime_checkable
class ExportFacadeContract(Protocol):
    def export_trajectory_bundle(self, name: str = 'trajectory_bundle.npz') -> Any: ...
    def export_trajectory(self, name: str = 'trajectory_bundle.npz') -> Any: ...
    def export_trajectory_metrics(self, name: str = 'trajectory_metrics.json', metrics: dict[str, object] | None = None) -> Any: ...
    def export_session(self, name: str = 'session.json', *, telemetry_detail: str = 'full') -> Any: ...
    def export_package(self, name: str = 'robot_sim_package.zip', *, telemetry_detail: str = 'minimal') -> Any: ...
    def export_benchmark(self, name: str = 'benchmark_report.json') -> Any: ...
    def export_benchmark_cases_csv(self, name: str = 'benchmark_cases.csv') -> Any: ...



@runtime_checkable
class ExportTaskView(Protocol):
    runtime_facade: RuntimeViewContract
    export_workflow: ExportWorkflowContract
    metrics_service: Any
    threader: Any

    def project_task_started(self, task_kind: str, message: str) -> None: ...
    def project_task_registered(self, task_id: str, task_kind: str) -> None: ...
    def project_export_messages(self, *messages: str) -> None: ...
    def on_worker_failed(self, failure) -> None: ...
    def on_worker_cancelled(self) -> None: ...


@runtime_checkable
class SceneTaskView(Protocol):
    runtime_facade: RuntimeViewContract
    threader: Any

    def build_scene_capture_request(self, path) -> dict[str, object]: ...
    def project_task_started(self, task_kind: str, message: str) -> None: ...
    def project_task_registered(self, task_id: str, task_kind: str) -> None: ...
    def project_scene_fit(self) -> None: ...
    def project_scene_path_cleared(self) -> None: ...
    def project_scene_capture(self, result) -> None: ...
    def read_scene_obstacle_request(self) -> dict[str, object] | None: ...
    def project_scene_obstacles_updated(self, scene) -> None: ...
    def on_worker_failed(self, failure) -> None: ...
    def on_worker_cancelled(self) -> None: ...


@runtime_checkable
class IKTaskView(Protocol):
    motion_workflow: MotionWorkflowContract
    metrics_service: Any
    threader: Any

    def read_ik_request(self) -> Any: ...
    def project_task_started(self, task_kind: str, message: str) -> None: ...
    def project_task_registered(self, task_id: str, task_kind: str) -> None: ...
    def project_busy_state(self, busy: bool, reason: str = '') -> None: ...
    def project_ik_result(self, result, summary: dict[str, object]) -> None: ...
    def on_ik_progress(self, payload) -> None: ...
    def on_ik_finished(self, result) -> None: ...
    def on_worker_failed(self, failure) -> None: ...
    def on_worker_cancelled(self) -> None: ...


@runtime_checkable
class TrajectoryTaskView(Protocol):
    motion_workflow: MotionWorkflowContract
    metrics_service: Any
    threader: Any

    def read_trajectory_request(self) -> Any: ...
    def project_task_started(self, task_kind: str, message: str) -> None: ...
    def project_task_registered(self, task_id: str, task_kind: str) -> None: ...
    def project_busy_state(self, busy: bool, reason: str = '') -> None: ...
    def project_trajectory_result(self, traj, metrics: dict[str, object], ee_points) -> None: ...
    def on_trajectory_finished(self, result) -> None: ...
    def on_worker_failed(self, failure) -> None: ...
    def on_worker_cancelled(self) -> None: ...


@runtime_checkable
class MainWindowActionView(Protocol):
    """Narrow contract consumed by ``MainWindowActionMixin``.

    The goal is to keep action handlers independent from the full window shell so future
    presentation splits do not require the old monolithic ``MainWindowLike`` surface.
    """

    status_panel: Any
    target_panel: Any
    robot_panel: Any
    playback_panel: Any
    scene_controller: Any
    plots_manager: Any
    playback_render_scheduler: Any
    robot_coordinator: Any
    playback_task_coordinator: Any
    scene_coordinator: Any
    export_task_coordinator: Any

    def _runtime_ops(self) -> RuntimeViewContract: ...
    def _robot_ops(self) -> RobotWorkflowContract: ...
    def _playback_ops(self) -> MotionWorkflowContract: ...
    def _run_presented(self, callback, *, title: str = '错误'): ...
    def _run_status_projected(self, callback, *, prefix: str): ...
    def _set_playback_running(self, running: bool) -> None: ...
    def _project_exception(self, exc: Exception | str, *, title: str = '错误') -> None: ...
    def _playback_status_text(self) -> str: ...
    def project_playback_frame(self, frame, live: bool = False) -> None: ...
    def read_robot_import_request(self) -> dict[str, object] | None: ...
    def project_robot_imported(self, result) -> None: ...


@runtime_checkable
class MainWindowTaskView(Protocol):
    """Narrow contract consumed by ``MainWindowTaskMixin``."""

    threader: Any
    status_panel: Any
    target_panel: Any
    solver_panel: Any
    benchmark_panel: Any
    scene_controller: Any
    plots_manager: Any
    metrics_service: Any
    ik_task_coordinator: Any
    trajectory_task_coordinator: Any
    benchmark_task_coordinator: Any
    status_coordinator: Any

    def _runtime_ops(self) -> RuntimeViewContract: ...
    def _solver_ops(self) -> MotionWorkflowContract: ...
    def _trajectory_ops(self) -> MotionWorkflowContract: ...
    def _playback_ops(self) -> MotionWorkflowContract: ...
    def _run_presented(self, callback, *, title: str = '错误'): ...
    def _set_busy(self, busy: bool, reason: str = '') -> None: ...
    def _build_solver_kwargs(self) -> dict[str, object]: ...
    def _playback_status_text(self) -> str: ...
    def _update_diagnostics_from_benchmark(self, summary: dict[str, object]) -> None: ...
    def _project_exception(self, exc: Exception | str, *, title: str = '错误') -> None: ...
    def project_trajectory_result(self, traj, metrics: dict[str, object], ee_points) -> None: ...


@runtime_checkable
class MainWindowUIContract(MainWindowActionView, MainWindowTaskView, Protocol):
    """UI-shell contract kept local to ``MainWindowUIMixin``.

    The UI mixin still needs a broad surface because it owns widget construction and
    projection methods, but that breadth is now localized instead of shared across all
    presentation mixins.
    """

    runtime_facade: RuntimeViewContract
    robot_workflow: RobotWorkflowContract
    motion_workflow: MotionWorkflowContract
    export_workflow: ExportWorkflowContract
    playback_threader: Any
    window_cfg: dict[str, object]
    diagnostics_panel: Any
    scene_widget: Any
    right_tabs: Any
    _error_boundary: Any

    def setCentralWidget(self, widget) -> None: ...
    def on_load_robot(self) -> None: ...
    def on_import_robot(self) -> None: ...
    def on_save_robot(self) -> None: ...
    def on_fill_current_pose(self) -> None: ...
    def on_run_fk(self) -> None: ...
    def on_run_ik(self) -> None: ...
    def on_cancel_ik(self) -> None: ...
    def on_plan(self) -> None: ...
    def on_play(self) -> None: ...
    def on_pause(self) -> None: ...
    def on_stop_playback(self) -> None: ...
    def on_step(self) -> None: ...
    def on_seek_frame(self, idx: int) -> None: ...
    def on_playback_speed_changed(self, value: float) -> None: ...
    def on_playback_loop_changed(self, checked: bool) -> None: ...
    def on_fit_scene(self) -> None: ...
    def on_clear_scene_path(self) -> None: ...
    def on_capture_scene(self) -> None: ...
    def on_add_scene_obstacle(self) -> None: ...
    def on_clear_scene_obstacles(self) -> None: ...
    def build_scene_capture_request(self, path) -> dict[str, object]: ...
    def read_scene_obstacle_request(self) -> dict[str, object] | None: ...
    def project_scene_obstacles_updated(self, scene) -> None: ...
    def on_run_benchmark(self) -> None: ...
    def on_export_trajectory(self) -> None: ...
    def on_export_session(self) -> None: ...
    def on_export_package(self) -> None: ...
    def on_export_benchmark(self) -> None: ...
    def _on_task_state_changed(self, snapshot) -> None: ...
